#commentout
#theme: jekyll-theme-minimal
name: シソネギ及びキャベツ
lead: Bookmark this to keep an eye on my blog updates!
desc: *desc
items:
- name: Pokemon
  href: /Pokemon
- name: Class B
  href: /Class_B
- name: Class C
  href: /Class_c
links:
- name: MyLinks
  href: /MyLinks
- name: dummy
  href: /dummy
jumps:
- name: twitter
  href: twiter
- name: download
  href: downloads
plugins:
- jekyll-sitemap
